### ISSUE TITLE
Crash after sending push Notification

### ISSUE THREAD

**Issue by marcohald** [privacyidea/keycloak-provider#87] opened 2022-01-25 09:54 UTC
I have configured the Keycloak Provider to prefer Push Tokens and use the Trigger Challenge Mode.
After I try to login the Push Token is sent to to my Phone and the Authentifiaction process crashes before the Push Message reaches my phone.
Then i get this Message on the Browser and the Push Notification appears on my phone.
![image](https://user-images.githubusercontent.com/10107699/150953546-a5adcb9b-eecd-4d8b-b2a9-73954da3a944.png)
This happens all in the same second after I Login, no matter what Push refresh interval I set

I'm using version 1.0.1 of the Provider
```
keycloak_1  | 09:44:38,968 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (default task-69) PrivacyIDEA SDK: Replacing privacyIDEA instance for realm master
keycloak_1  | 09:44:38,968 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (pool-27-thread-1) PrivacyIDEA SDK: Sending to /auth
keycloak_1  | 09:44:38,969 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (pool-27-thread-1) PrivacyIDEA SDK: username=trigger-admin
keycloak_1  | 09:44:38,969 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (pool-27-thread-1) PrivacyIDEA SDK: password=********************************
keycloak_1  | 09:44:38,969 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (pool-27-thread-1) PrivacyIDEA SDK: realm=admin
keycloak_1  | 09:44:39,618 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (pool-27-thread-1) PrivacyIDEA SDK: Sending to /validate/triggerchallenge
keycloak_1  | 09:44:39,618 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (pool-27-thread-1) PrivacyIDEA SDK: user=marco.hald
keycloak_1  | 09:44:39,618 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (pool-27-thread-1) PrivacyIDEA SDK: realm=intra
keycloak_1  | 09:44:39,885 INFO  [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (OkHttp https://privacyidea.example.com/...) PrivacyIDEA SDK: /validate/triggerchallenge:
keycloak_1  | {
keycloak_1  |   "detail": {
keycloak_1  |     "message": "Please confirm the authentication on your mobile device!",
keycloak_1  |     "messages": [
keycloak_1  |       "Please confirm the authentication on your mobile device!"
keycloak_1  |     ],
keycloak_1  |     "multi_challenge": [
keycloak_1  |       {
keycloak_1  |         "message": "Please confirm the authentication on your mobile device!",
keycloak_1  |         "serial": "PIPU0183D727",
keycloak_1  |         "transaction_id": "11924735609730743657",
keycloak_1  |         "type": "push"
keycloak_1  |       }
keycloak_1  |     ],
keycloak_1  |     "serial": "PIPU0183D727",
keycloak_1  |     "threadid": 139964220491520,
keycloak_1  |     "transaction_id": "11924735609730743657",
keycloak_1  |     "transaction_ids": [
keycloak_1  |       "11924735609730743657"
keycloak_1  |     ],
keycloak_1  |     "type": "push"
keycloak_1  |   },
keycloak_1  |   "id": 1,
keycloak_1  |   "jsonrpc": "2.0",
keycloak_1  |   "result": {
keycloak_1  |     "status": true,
keycloak_1  |     "value": 1
keycloak_1  |   },
keycloak_1  |   "time": 1643103931.9763248,
keycloak_1  |   "version": "privacyIDEA None",
keycloak_1  |   "signature": "rsa_sha256_pss:9787b29279c136c99a845fc0f89357d3fd7c7545d5fecb122f6f9267579cc7ce39a8b446319b341f719a867c33c131c50324bc77f7bb1cbd4b08a7f9c8ab467fd142e08bf165c3a8cd86f6476d3256b800c0c82e9d997856148833036276b730e72e2ddc59678cd84dc84158660b994f7fcb65be29f158b8279caba909a95bd9ac029769e9b1c1df984dd739ea33f2d1d9d9f604a6c607cf160293ca3e763a9945db221c54a1e776dc4d1a6e52027b88d438e7a8f1faddead553eec8367c20cabe7fb0b343284a3b619c9129274374d6e4dee2a1fa11eefba216a6fcdb6b2ddf9b4e1a838d7d66ab4b34e6878f329f3ffbdd2b87e43d4c051e3e3d6682de253c"
keycloak_1  | }
keycloak_1  | 09:44:39,886 WARN  [org.keycloak.services] (default task-69) KC-SERVICES0013: Failed authentication: java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonPrimitive (com.google.gson.JsonNull and com.google.gson.JsonPrimitive are in unnamed module of loader 'deployment.PrivacyIDEA-Provider.jar' @7d657794)
keycloak_1  | 	at deployment.PrivacyIDEA-Provider.jar//com.google.gson.JsonObject.getAsJsonPrimitive(JsonObject.java:172)
keycloak_1  | 	at deployment.PrivacyIDEA-Provider.jar//org.privacyidea.JSONParser.getString(JSONParser.java:508)
keycloak_1  | 	at deployment.PrivacyIDEA-Provider.jar//org.privacyidea.JSONParser.parsePIResponse(JSONParser.java:149)
keycloak_1  | 	at deployment.PrivacyIDEA-Provider.jar//org.privacyidea.PrivacyIDEA.triggerChallenges(PrivacyIDEA.java:270)
keycloak_1  | 	at deployment.PrivacyIDEA-Provider.jar//org.privacyidea.authenticator.PrivacyIDEAAuthenticator.authenticate(PrivacyIDEAAuthenticator.java:188)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:446)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:253)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:389)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:186)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:164)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:950)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:312)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:283)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:267)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:340)
keycloak_1  | 	at jdk.internal.reflect.GeneratedMethodAccessor708.invoke(Unknown Source)
keycloak_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
keycloak_1  | 	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
keycloak_1  | 	at org.keycloak.keycloak-wildfly-extensions@16.1.0//org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
keycloak_1  | 	at org.keycloak.keycloak-wildfly-extensions@16.1.0//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
keycloak_1  | 	at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
keycloak_1  | 	at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
keycloak_1  | 	at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
keycloak_1  | 	at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
keycloak_1  | 	at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
keycloak_1  | 	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
keycloak_1  | 	at io.undertow.core@2.2.14.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
keycloak_1  | 	at org.jboss.xnio@3.8.5.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
keycloak_1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
keycloak_1  | 
keycloak_1  | 09:44:39,898 WARN  [org.keycloak.events] (default task-69) type=LOGIN_ERROR, realmId=master, clientId=laps, userId=null, ipAddress=10.134.250.4, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://app.example.com/auth, code_id=02d0bb16-5f7a-46fa-8bdd-6ce92aed6f55, username=marco.hald, authSessionParentId=02d0bb16-5f7a-46fa-8bdd-6ce92aed6f55, authSessionTabId=-1Lzk74sqmA

```

**Comment by nilsbehlen** [comment] 2022-01-25 10:07
Hi,
thanks for reporting this. I will upload a version that fixes this soon

**Comment by nilsbehlen** [comment] 2022-01-25 10:09
Also what version of privacyIDEA are you using? The reponse is missing a field and does not specify the version

**Comment by marcohald** [comment] 2022-01-25 10:38
I use the deb from the Enterprise Repo in version 3.6.3-1bionic

**Comment by nilsbehlen** [comment] 2022-01-25 15:29
Hi, unfortunately i was not able to reproduce the error using the response you were getting from privacyIDEA.
Therefore i just added some more checks to prevent such crash. Can you try this version
[PrivacyIDEA-Provider.zip](https://github.com/privacyidea/keycloak-provider/files/7934838/PrivacyIDEA-Provider.zip) and post the logs again if it still fails?

**Comment by marcohald** [comment] 2022-01-26 07:52
It is working now and a new Error Message about the Version appeared
```
keycloak_1  | 07:20:52,253 ERROR [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (default task-1) PrivacyIDEA SDK: Cannot get versionnumber from JSON
keycloak_1  | 07:20:52,254 ERROR [org.privacyidea.authenticator.PrivacyIDEAAuthenticator] (default task-1) PrivacyIDEA SDK: : java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonPrimitive (com.google.gson.JsonNull and com.google.gson.JsonPrimitive are in unnamed module of loader 'deployment.PrivacyIDEA-Provider.jar' @183b1694)
```
Where can I check why there is no version in the json?

**Comment by nilsbehlen** [comment] 2022-01-26 08:30
Hi,
i made it still display the error but not crash when it happens. Good to hear it works now.
I don't really know why the server does not send the versionNumber and also sends "version": "privacyIDEA None", especially since its from the official repo. I will ask my colleagues about this.

**Comment by nilsbehlen** [comment] 2022-01-26 09:06
It might be that the metadata of your python virtualenv is incorrect or missing information about the privacyidea package. How did you install privacyidea?

**Comment by marcohald** [comment] 2022-01-26 10:42
Via apt-get from the Enterprise Repo

**Comment by nilsbehlen** [comment] 2022-01-26 15:13
Ok that should not be happening. However, that issue is not related to this project and i am not proficient with the matter. So I will close this issue and have the solution to the inital problem included in the next release of the provider.

If you require the versionNumber problem to be resolved, please open a support ticket or post at https://community.privacyidea.org/.

**Comment by nilsbehlen** [comment] 2022-01-26 15:15
https://github.com/privacyidea/java-client/issues/29

**Closed by nilsbehlen** 2022-01-26 15:15 UTC
